get rents with filters
---
tags:
  - Rents
parameters:
  - name: type_operations
    in: path
    type: string
    required: true
    description: Type of operations (e.g., rent, buy)
  - name: page
    in: query
    type: integer
    required: false
    description: Page number for paginating results
  - name: tipos
    in: query
    type: string
    required: false
    description: Types filter
  - name: zonas
    in: query
    type: string
    required: false
    description: Zones filter
  - name: dormitorios
    in: query
    type: integer
    required: false
    description: Bedrooms filter
  - name: baños
    in: query
    type: integer
    required: false
    description: Bathrooms filter
  - name: orden
    in: query
    type: string
    required: false
    description: Sorting order
  - name: moneda
    in: query
    type: string
    required: false
    description: Currency filter
  - name: min_max
    in: query
    type: string
    required: false
    description: Price range filter
  - name: area
    in: query
    type: string
    required: false
    description: Area range filter
responses:
  200:
    description: Successful request
    schema:
      properties:
        rents:
          type: array
          items:
            type: object
            properties:
              __class__:
                type: string
              created_at:
                type: string
                description: Time of creation of the instance
              updated_at:
                type: string
                description: Time of last update of the instance
              id:
                type: string
                description: The uuid of the instance
              state_id:
                type: string
                description: UUID of the city's state
              name:
                type: string
                description: City name
              # Add other properties as needed
        page:
          type: integer
          description: Current page number
        filters:
          type: object
          description: Filters applied to the request
        entries_per_page:
          type: integer
          description: Number of entries per page
        total_results:
          type: integer
          description: Total number of results
