get count municipalities
---
tags:
  - Rents
parameters:
  - name: type_operations
    in: path
    type: string
    required: true
    description: Type of operations (e.g., rent, buy)
responses:
  200:
    description: Successful request
    schema:
      properties:
        rents:
          type: array
          items:
            type: object
            properties:
              __class__:
                type: string
              created_at:
                type: string
                description: Time of creation of the instance
              updated_at:
                type: string
                description: Time of last update of the instance
              id:
                type: string
                description: The uuid of the instance
              # Add other properties as needed
        filters:
          type: object
          description: Filters applied to the request
        total_results:
          type: integer
          description: Total number of results
